import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';

const plate=document.querySelector('.plate'), sceneEl=document.getElementById('scene');
const loadmsg=document.getElementById('loadmsg'), bar=document.getElementById('bar'), retry=document.getElementById('retry');
const sizes={'meta.json':68179,'positions.bin':1671060,'1-attrs.bin':417765,'2-w.bin':743322,'4-e0.bin':1486648,'5-e1.bin':1486648,'6-e2.bin':1486648,'7-e3.bin':1486632};
const total=Object.values(sizes).reduce((a,b)=>a+b,0); let loaded={},failed=false;
function progress(){if(failed)return;const bytes=Object.values(loaded).reduce((a,b)=>a+b,0);bar.style.width=(100*bytes/total).toFixed(1)+'%';loadmsg.textContent=`Loading connectome geometry · ${(bytes/1048576).toFixed(1)} MB of ${(total/1048576).toFixed(1)} MB`;}
async function get(url){const r=await fetch(url,{cache:'force-cache'});if(!r.ok)throw new Error(`${url} returned ${r.status}`);if(!r.body){const b=await r.arrayBuffer();loaded[url]=b.byteLength;progress();return b}const reader=r.body.getReader(),chunks=[];let n=0;for(;;){const {done,value}=await reader.read();if(done)break;chunks.push(value);n+=value.byteLength;loaded[url]=n;progress()}const out=new Uint8Array(n);let o=0;for(const c of chunks){out.set(c,o);o+=c.length}return out.buffer}
const typed=(b,t)=>t==='f32'?new Float32Array(b):t==='u32'?new Uint32Array(b):t==='i8'?new Int8Array(b):new Uint8Array(b);
let renderer,frame;
async function init(){retry.style.display='none';loaded={};failed=false;progress();plate.classList.remove('ready');sceneEl.innerHTML='';try{
const meta=JSON.parse(new TextDecoder().decode(await get('meta.json'))),N=meta.neuron_count,E=meta.edge_count;
const files=await Promise.all([get('positions.bin'),get('1-attrs.bin'),get('2-w.bin'),get('4-e0.bin'),get('5-e1.bin'),get('6-e2.bin'),get('7-e3.bin')]);
const positions=typed(files[0],'f32'),attrs=typed(files[1],'u8'),wI8=typed(files[2],'i8'),chunks=files.slice(3).map(b=>new Uint8Array(b));
const edgeBytes=new Uint8Array(chunks.reduce((s,c)=>s+c.length,0));let eo=0;for(const c of chunks){edgeBytes.set(c,eo);eo+=c.length}const edgesU=new Uint32Array(edgeBytes.buffer);
loadmsg.textContent='Building the interactive plate.';
const act=new Float32Array(N),next=new Float32Array(N),Epre=new Uint32Array(E),Epost=new Uint32Array(E),Ew=new Float32Array(E);
for(let e=0;e<E;e++){Epre[e]=edgesU[2*e];Epost[e]=edgesU[2*e+1];Ew[e]=wI8[e]/320}
const outStart=new Uint32Array(N+1);for(let e=0;e<E;e++)outStart[Epre[e]+1]++;for(let i=0;i<N;i++)outStart[i+1]+=outStart[i];
const csrPost=new Uint32Array(E),csrW=new Float32Array(E),cursor=outStart.slice(0,N);for(let e=0;e<E;e++){const p=Epre[e],o=cursor[p]++;csrPost[o]=Epost[e];csrW[o]=Ew[e]}for(let i=0;i<N;i++){const f=1/(1+(outStart[i+1]-outStart[i])*.06);for(let o=outStart[i];o<outStart[i+1];o++)csrW[o]*=f}
const scene=new THREE.Scene();scene.background=new THREE.Color(0xf3f0e8);const camera=new THREE.PerspectiveCamera(48,plate.clientWidth/plate.clientHeight,.1,4000);camera.position.set(0,55,430);
renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});renderer.setSize(plate.clientWidth,plate.clientHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;sceneEl.appendChild(renderer.domElement);
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.07;controls.autoRotate=true;controls.autoRotateSpeed=.28;controls.target.set(0,15,0);controls.minDistance=150;controls.maxDistance=700;
const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.BufferAttribute(positions,3));const aAct=new Float32Array(N),actAttr=new THREE.BufferAttribute(aAct,1);actAttr.setUsage(THREE.DynamicDrawUsage);geo.setAttribute('aAct',actAttr);
const ptsMat=new THREE.ShaderMaterial({uniforms:{uPx:{value:renderer.getPixelRatio()}},vertexShader:`attribute float aAct;uniform float uPx;varying float vA;void main(){vA=aAct;vec4 mv=modelViewMatrix*vec4(position,1.);gl_PointSize=clamp((1.15+aAct*3.)*uPx*(300./-mv.z),1.,9.);gl_Position=projectionMatrix*mv;}`,fragmentShader:`varying float vA;void main(){vec2 d=gl_PointCoord-.5;if(length(d)>.5)discard;vec3 ink=vec3(.09,.09,.085),red=vec3(.769,.259,.184);gl_FragColor=vec4(mix(ink,red,clamp(vA,0.,1.)),.55+clamp(vA,0.,1.)*.4);}`,transparent:true,depthWrite:false,blending:THREE.NormalBlending});
const brain=new THREE.Points(geo,ptsMat);brain.position.y=15;scene.add(brain);
const stride=7,RE=Math.floor(E/stride),lpos=new Float32Array(RE*6),lact=new Float32Array(RE*2),edgePre=new Uint32Array(RE);for(let k=0;k<RE;k++){const e=k*stride,p=Epre[e],q=Epost[e];edgePre[k]=p;lpos.set([positions[3*p],positions[3*p+1],positions[3*p+2],positions[3*q],positions[3*q+1],positions[3*q+2]],k*6)}
const lgeo=new THREE.BufferGeometry();lgeo.setAttribute('position',new THREE.BufferAttribute(lpos,3));const lactAttr=new THREE.BufferAttribute(lact,1);lactAttr.setUsage(THREE.DynamicDrawUsage);lgeo.setAttribute('aAct',lactAttr);const lmat=new THREE.ShaderMaterial({vertexShader:`attribute float aAct;varying float vA;void main(){vA=aAct;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}`,fragmentShader:`varying float vA;void main(){vec3 ink=vec3(.14,.13,.12),red=vec3(.769,.259,.184);gl_FragColor=vec4(mix(ink,red,clamp(vA,0.,1.)),.07+clamp(vA,0.,1.)*.5);}`,transparent:true,depthWrite:false,blending:THREE.NormalBlending});const wires=new THREE.LineSegments(lgeo,lmat);wires.position.y=15;scene.add(wires);
const presets=meta.presets;let stim=null;const labels={vision:'Vision',descend:'Escape',sensory:'Odor',ascending:'Memory',motor:'Navigate'};
function stimulate(name,arr,strength=1,dur=2200){stim={arr,strength,until:performance.now()+dur};document.getElementById('selected').textContent=labels[name]||'Local probe';document.querySelectorAll('.sbtn').forEach(b=>b.classList.toggle('hot',b.dataset.p===name))}
document.querySelectorAll('[data-p]').forEach(b=>b.addEventListener('click',()=>{const p=b.dataset.p;if(p==='reset'){act.fill(0);stim=null;document.getElementById('selected').textContent='None';document.querySelectorAll('.sbtn').forEach(x=>x.classList.remove('hot'))}else stimulate(p,presets[p],p==='descend'||p==='motor'?1.5:1)}));
const ray=new THREE.Raycaster(),ptr=new THREE.Vector2();let down=0;renderer.domElement.addEventListener('pointerdown',()=>down=performance.now());renderer.domElement.addEventListener('pointerup',ev=>{if(performance.now()-down>220)return;const rect=renderer.domElement.getBoundingClientRect();ptr.set(((ev.clientX-rect.left)/rect.width)*2-1,-((ev.clientY-rect.top)/rect.height)*2+1);ray.setFromCamera(ptr,camera);const ro=ray.ray.origin,rd=ray.ray.direction;let best=-1,bestD=12;for(let i=0;i<N;i++){const dx=positions[3*i]-ro.x,dy=positions[3*i+1]+15-ro.y,dz=positions[3*i+2]-ro.z,t=dx*rd.x+dy*rd.y+dz*rd.z;if(t<0)continue;const px=dx-t*rd.x,py=dy-t*rd.y,pz=dz-t*rd.z,d=Math.hypot(px,py,pz);if(d<bestD){bestD=d;best=i}}if(best>=0){const bx=positions[3*best],by=positions[3*best+1],bz=positions[3*best+2],nb=[];for(let i=0;i<N;i+=3){const dx=positions[3*i]-bx,dy=positions[3*i+1]-by,dz=positions[3*i+2]-bz;if(dx*dx+dy*dy+dz*dz<196)nb.push(i)}stimulate('probe',nb,1.4,1600);toast(`${nb.length.toLocaleString()} nearby neurons stimulated`)}});
let toastTimer;function toast(s){const t=document.getElementById('toast');t.textContent=s;t.style.opacity=1;clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.style.opacity=0,1400)}
const clock=new THREE.Clock();function step(dt){const decay=Math.pow(.06,dt);for(let i=0;i<N;i++)act[i]*=decay;const now=performance.now();if(stim&&now<stim.until){const s=stim.strength*dt*5.5;for(const i of stim.arr)act[i]=Math.min(act[i]+s*(.6+Math.random()*.8),1.4)}else if(stim){stim=null;document.querySelectorAll('.sbtn').forEach(x=>x.classList.remove('hot'))}next.fill(0);for(let i=0;i<N;i++)if(act[i]>.6){const a=act[i];act[i]=a*.35;for(let o=outStart[i];o<outStart[i+1];o++)next[csrPost[o]]+=a*csrW[o]}let active=0;for(let i=0;i<N;i++)if(next[i]>.12)active++;const damp=active>15000?.2:1;for(let i=0;i<N;i++){let v=act[i]+next[i]*damp;act[i]=v>1.2?1.2:v<.02?0:v}}
function animate(){frame=requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.05);step(dt);for(let i=0;i<N;i++)aAct[i]=act[i];actAttr.needsUpdate=true;for(let k=0;k<RE;k++){const a=act[edgePre[k]];lact[2*k]=a;lact[2*k+1]=a*.6}lactAttr.needsUpdate=true;controls.update();renderer.render(scene,camera)}
document.getElementById('n-count').textContent=N.toLocaleString();document.getElementById('e-count').textContent=E.toLocaleString();plate.classList.add('ready');animate();setTimeout(()=>stimulate('vision',presets.vision,.75,1300),1800);
const resize=()=>{if(!renderer)return;camera.aspect=plate.clientWidth/plate.clientHeight;camera.updateProjectionMatrix();renderer.setSize(plate.clientWidth,plate.clientHeight)};new ResizeObserver(resize).observe(plate);
}catch(err){failed=true;console.error(err);loadmsg.textContent='The visualization could not load. The study and sources remain available below.';retry.style.display='inline-block';bar.style.width='0'}}
retry.addEventListener('click',()=>{if(frame)cancelAnimationFrame(frame);if(renderer)renderer.dispose();init()});init();
